### ISSUE TITLE
dev: improve test coverage

### ISSUE THREAD

**Issue by EvolveArt** [petscheit/madara-js-tests#2]
**Current Behavior**

These tests cover a limited scope of actions.

**Expected Behavior**

We can leverage the work of starknet.js [tests](https://github.com/starknet-io/starknet.js/tree/develop/__tests__) in order to increase the scope of actions covered.
It will of course need to be adapted to Madara specifities but it will probably help catch more edge cases.

**Comment by ybensacq** [comment]
@EvolveArt ok you can assign to me.

**Comment by EvolveArt** [comment]
Lots of progress made with #4 #3
